project:
  type: composite

outputs:
  book:
    type: book
    output-dir: "docs"
    title: "DSI ML workshop"
    author: "Prajeet Bajpai and Varada Kolhatkar"
    date: "2024-08-24"    
    chapters:
      - index.qmd
      - modules/03_deep-learning.qmd
      - modules/04_unsupervised-learning.qmd
  slides:
    type: revealjs
    output-dir: "slides"
    input-files:
      - slides/index.qmd
      - slides/03_deep-learning.qmd
      - slides/04_unsupervised-learning.qmd      

      