project:
  type: book

book:
  title: "DSI ML workshop"
  author: "Prajeet Bajpai and Varada Kolhatkar"
  date: "2024-08-15"
  chapters:
    - index.qmd
    - modules/pre-activity.qmd
    - modules/01_supervised-learning.ipynb
    - modules/02_more-supervised-learning.ipynb
    - modules/03_deep-leaning.ipynb
    - modules/04_unsupervised-learning.ipynb
    - modules/05_LLMs.ipynb
    - modules/post-activity.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



