project:
  type: website
  preview:
    port: 12345
  render:
    - "./*.qmd"
    - "slides/*.qmd"
    - "about/index.qmd"
  resources:
    - slides

website:
  title: "DSI Machine Learning Workshop"
  description: "Examine whether machine learning is suitable for your projects"
  site-url: https://kvarada.github.io/DSI-ML-workshop-2024/

  repo-url: https://github.com/kvarada/DSI-ML-workshop-2024/
  repo-subdir: website
  
  navbar:
    title: "DSI Machine Learning Workshop"
    left:
      - href: index.qmd
        text: Home
      - href: workshop.qmd
        text: Workshop
      - href: about/index.qmd
        text: Team
  
  page-navigation: true
  
  sidebar:
    - id: workshop
      contents:
        - workshop.qmd        
        - workshop-01.qmd
        - workshop-02.qmd
        - workshop-04.qmd
        
format:
  html:
    theme: [zephyr]
    toc: false
    lightbox: true
          
editor:
  render-on-save: true

execute:
  freeze: auto