---
title: "Topics and Data Sources for Machine Learning applications"
format: 
    revealjs:
      smaller: true
      center: true
---

## Potential Topics for Machine Learning Projects

Below are some sectors and topics of real-world issues that could possibly be solved using Machine Learning

### Business

#### Finance

-   forecast the direction of stock market index price change based on financial indicators
-   detect potentially fraudulent transactions of credit cards

#### Marketing

-   estimate the effectiveness of a marketing campaign by predicting customer action (click/not click, purchase/not purchase, etc.)
-   predict whether a customer will churn after a certain period of time
-   customer segmentation based on user behaviors on social media platform for targeted marketing

### Science & Engineering

#### Biology

-   identify and classify genomic sequences from DNA samples
-   identify and detect malignant tumors cell based on histology imaging

#### Structural Engineering

-   predict the risk of building/facility collapse when earthquake occurs based on key indicators and building images

### Social Science

#### Psychology

-   estimate how likely a person has autism or other developmental disorder based on personal traits and history

#### Public Health

-   forecast the CO2 emission of a country based on the country's statistics (demographics, economic activity, etc.)
-   predict the risk of cardiovascular disease of an individual based on key health indicators


## Common Open Data Source for Machine Learning Projects

Below are some open data sources that could be used for Machine Learning projects

### General

-   [UCI Machine Learning Repository](https://archive.ics.uci.edu/datasets)
-   [Kaggle](https://www.kaggle.com/datasets)

### Business

-   [Federal Reserve Bank of St. Louis](https://fred.stlouisfed.org/)

### Science & Engineering

-   [National Library of Medicine](https://pubchem.ncbi.nlm.nih.gov/)

### Social Science

-   [Gapminder](https://www.gapminder.org/data/)
-   [The Humanitarian Data Exchange (HDX)](https://data.humdata.org/dataset)
-   [Statistics Canada](https://www150.statcan.gc.ca/n1/en/type/data?MM=1#tables)