---
title: ML Problem Framing
description: Frame your problems as machine learning problems 
description-short: Lab session 
duration: 1.5 hours
time: 2:00 - 3:30

editor: { render-on-save: true }
---

You can choose a dataset and try to address the following questions:

-   Is the provided dataset appropriate for the specified objective? What type of data would ideally solve your problem or research question? Are there better-suited datasets available on the internet for this objective?
-   Clearly define the expected input and the 'ideal' output. Determine if machine learning is the appropriate method for addressing this problem.
-   If machine learning is deemed suitable, what should the model aim to achieve? How would you measure the model's performance?
-   How would a human tackle this issue? Can you propose any heuristic methods to solve this problem?
-   What are the major steps required to resolve this problem?
-   Draw a diagram that illustrates the input, output, and key stages of the problem-solving process.
-   Which type of machine learning would be best suited for your problem?
-   What specific machine learning technique would be most effective for this problem?

### Common Open Data Source for Machine Learning Projects

Below are some open data sources that could be used for Machine Learning projects

-   [UCI Machine Learning Repository](https://archive.ics.uci.edu/datasets)
-   [Kaggle](https://www.kaggle.com/datasets)
-   [Federal Reserve Bank of St. Louis](https://fred.stlouisfed.org/)
-   [National Library of Medicine](https://pubchem.ncbi.nlm.nih.gov/)
-   [Gapminder](https://www.gapminder.org/data/)
-   [The Humanitarian Data Exchange (HDX)](https://data.humdata.org/dataset)
-   [Statistics Canada](https://www150.statcan.gc.ca/n1/en/type/data?MM=1#tables)